name: Build on Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo Build Message
        run: echo "Simulando uma compilação após um push"
