name: Agendar Hello World

on:
  schedule:
    - cron: "10 23 * * *" # Executa às 23:10 UTC todos os dias

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Manda um Hello
        run: echo "Hello World! Este é um workflow agendado."
